import React from "react";
import Search from "./components/Search";
import { Metadata } from "next";

type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Search Page",
  description: "Generated by create next app",
};

function SearchLayout({ children }: Props) {
  return (
    <div className="flex divide-x-2 p-5">
      <div>
        <h1>Search</h1>
      </div>
      <div className="flex-1 pl-5">
        <Search />
        <div className="w-full">{children}</div>
      </div>
    </div>
  );
}

export default SearchLayout;
